### ISSUE TITLE
NooBaa BackingStores and BucketClasses in status Rejected

### ISSUE THREAD

**Issue by computate** [OCP-on-NERC/operations#102]
NooBaa errors started on Sun Apr 2, 2023 14:42 PM, see [https://console-openshift-console.apps.nerc-ocp-infra.rc.fas.harvard.edu/monitoring/alerts/2191382530?alertna[…]e=loki_api_v1_push&severity=critical](see the monitoring alerts here)
![image](https://user-images.githubusercontent.com/15114160/229593505-220becc6-4c14-445f-a8f2-4ce4ad085b08.png)

- See all the NooBaa BackingStores are affected
![image](https://user-images.githubusercontent.com/15114160/229593763-9016ea9a-31c5-42ad-8faa-1d41ed663fc3.png)

- See all the NooBaa BucketClasses
![image](https://user-images.githubusercontent.com/15114160/229593892-01dc53e6-6a03-4b02-9b9b-c03a646dba72.png)

# History
- Sun Apr 2, 2023 14:42 PM
- This also happened the weekend of Sun Feb 12, 2023.

**Comment by larsks** [comment]
I've started running a [must-gather](https://docs.openshift.com/container-platform/4.10/support/gathering-cluster-data.html) in preparation for opening a support case. I'll be taking a closer look at the logs after our 2:30.

**Comment by larsks** [comment]
I've opened a severity 2 support case for this issue: https://access.redhat.com/support/cases/#/case/03478695

We are experiencing some difficulties running the `oc adm must-gather` command, so we'll have at least one extra round trip with support trying to figure out that issue first.

**Comment by larsks** [comment]
It looks like we're actually having problems with volume storage. When attempting to create a new PVC it's getting stuck in "Pending" status:

```
$ k get pvc example-pvc
NAME          STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS                           AGE
example-pvc   Pending                                      ocs-external-storagecluster-ceph-rbd   30s
```

This means we need to investigate the Ceph side of things.

**Comment by larsks** [comment]
Ceph status reports:

```
  cluster:
    id:     6de96983-eef7-4690-9a6d-9124d3707a30
    health: HEALTH_WARN
            1 pool(s) full
            1 pools have many more objects per pg than average
            clients are using insecure global_id reclaim
            mons are allowing insecure global_id reclaim

  services:
    mon: 5 daemons, quorum mon02,mon05,mon01,mon03,mon04 (age 3d)
    mgr: mon05(active, since 7d), standbys: mon04, mon03
    mds: cephfs:1 {0=mds03=up:active} 2 up:standby
    osd: 2326 osds: 2070 up (since 5d), 2037 in (since 8d)
    rgw: 3 daemons active (186872227, 186872233, 186950736)

  task status:

  data:
    pools:   48 pools, 37712 pgs
    objects: 2.05G objects, 6.4 PiB
    usage:   9.7 PiB used, 13 PiB / 23 PiB avail
    pgs:     37644 active+clean
             66    active+clean+scrubbing+deep
             2     active+clean+scrubbing

  io:
    client:   159 MiB/s rd, 97 MiB/s wr, 1.15k op/s rd, 714 op/s wr
```
