### ISSUE TITLE
Fix hardware issues on workers

### ISSUE THREAD

**Issue by joachimweyl** [OCP-on-NERC/operations#111]
Multiple Alerts are coming up for our nerc-ocp-prod hardware that we should look into. The question arises should we order new parts and wait for them or order new parts and see if we can pull these parts out of the other chassis we have and then put the ordered hardware into the chassis we borrowed them from?
```
---
cmc:
  - name: cmc-0-obm.nerc-ocp-prod.rc.fas.harvard.edu
    serial: HBR51Q2
    critical_alerts:
      - source: "Fan-5"
        alarm:
          - "Fan 5 RPM is less than the lower critical threshold."
  - name: cmc-1-obm.nerc-ocp-prod.rc.fas.harvard.edu
    serial: JVDFDH2
    critical_alerts:
      - source: "Chassis"
        alarm:
          - "Fan 1 is removed."
      - source: "Fan-5"
        alarm:
          - "Fan 5 RPM is less than the lower critical threshold."
  - name: cmc-2-obm.nerc-ocp-prod.rc.fas.harvard.edu
    serial: 4X671Q2
    observed_issues:
      - "Server overview page complains about idrac license"
  - name: cmc-3-obm.nerc-ocp-prod.rc.fas.harvard.edu
    serial: JVD8KH2
    critical_alerts:
      - source: "Fan-1"
        alarm:
          - "Fan 1 RPM is less than the lower critical threshold."
      - source: "Fan-5"
        alarm:
          - "Fan 5 RPM is less than the lower critical threshold."
  - name: cmc-4-obm.nerc-ocp-prod.rc.fas.harvard.edu
    serial: 50R5LH2
    observed_issues:
      - issue: "cmc chassis does not see any nodes in it's slots"
  - name: cmc-6-obm.nerc-ocp-prod.rc.fas.harvard.edu
    serial: JG79KH2
    critical_alerts:
      - source: "Fan-5"
        alarm:
          - "Fan 5 RPM is less than the lower critical threshold."
    non_critical_alerts:
      - source: "PSU-1"
        alarm:
          - "Cannot obtain status information from power supply 1."
          ```
