### ISSUE TITLE
Confirm vault PV configuration

### ISSUE THREAD

**Issue by larsks** [OCP-on-NERC/operations#115]
In theory our vault configuration is request 10Gi per pod:

```
volumeClaimTemplates:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    name: data
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: kubevirt-hostpath-provisioner
    volumeMode: Filesystem
  status:
    phase: Pending
```

But the existing PVCs are much larger:

```
$ k -n vault get pvc
NAME                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                           AGE
data-nerc-vault-0   Bound    pvc-ae83e43a-8d13-4797-b6d0-7a2dcd1d4515   446Gi      RWO            kubevirt-hostpath-provisioner          75d
data-nerc-vault-1   Bound    pvc-dcbea7c7-de84-4754-87f0-0c181f535d9e   446Gi      RWO            kubevirt-hostpath-provisioner          75d
data-nerc-vault-2   Bound    pvc-05b9359f-5a95-46b7-b771-eb327d0fbca2   446Gi      RWO            kubevirt-hostpath-provisioner          75d
vault-snapshots     Bound    pvc-f9391fcd-65df-4e49-905b-d2a73acd6100   10Gi       RWO            ocs-external-storagecluster-ceph-rbd   75d
```

It looks like we're requesting 1.5TB for vault storage, which seems excessive. We should take a closer look at the deployed configuration and ensure the PV sizes matches are expectations.
