### ISSUE TITLE
Investigate support for OIDC group sync in OpenShift

### ISSUE THREAD

**Issue by larsks** [OCP-on-NERC/operations#116]
It looks like with OpenShift 4.10 and later that there is support for synchronizing groups from the OIDC provider. In the past this wasn't available. This may be useful in particular where we're using Keycloak, but it's worth checking to see if we could also use this for synchronizing with GitHub teams (which we're currently handling with a "group sync operator").

**Comment by computate** [comment]
@larsks could you please point me to the docs for synchronizing OIDC groups? I tried a few months ago syncing keycloak with the group sync operator, but it failed to match "preferred usernames" that the group sync operator looks up from keycloak with the "sub" user uuid that keycloak assigns as a unique ID. I confirmed on CoreOS Slack that OpenShift forces the user names to be the "sub", rather than "preferred username", so the group sync operator doesn't seem to work with keycloak. But if you can share the docs for this other option, I'd be happy to test it out.

**Comment by larsks** [comment]
@computate that's basically what this issue is about -- figuring out whether or not it's possible to perform group synchronization against an OIDC service provider, and if so, how. Anything I figure out I'll add to this issue.

**Comment by computate** [comment]
@larsks In case it helps building keycloak into NERC OpenShift, I have already created my own set of RH SSO Operator manifests here. It includes applications, operatorgroups, namespaces, subscriptions, externalsecrets, keycloaks, keycloakusers, keycloakrealms, keycloakclients, oauths, and more: https://github.com/computate-org/smartabyar-smartvillage/tree/main/openshift/kustomize/bundles/sso

**Comment by larsks** [comment]
# Group synchronization with KeyCloak

Starting with version 4.10, OpenShift supports synchronizing groups against an external OIDC identity provider.

In the following examples, I'm configuring a fresh [OpenShift Local](https://developers.redhat.com/products/openshift-local/overview) installation to sync groups against a Keycloak instance hosted at `keycloak.services.house`.

## Configuration

### Configuring OpenShift

On the OpenShift side, you need to set the name of the groups claim in the OAuth configuration. See the `claims` section in the following manifest:

```
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - mappingMethod: claim
    name: house
    openID:
      ca:
        name: house-oauth-ca
      claims:
        email:
        - email
        name:
        - name
        preferredUsername:
        - preferred_username
        groups:
        - groups
      clientID: crc
      clientSecret:
        name: house-oauth-clientsecret
      issuer: https://keycloak.services.house/realms/house
    type: OpenID
  templates:
    login:
      name: login-template
  tokenConfig:
    accessTokenMaxAgeSeconds: 0
```

### Configuring keycloak

On the keycloak side, we need to:

1. Create a client scope for the group information
2. Enable that scope for the openshift client

## Demonstration

Initially, we have no groups defined in OpenShift:

```
$ k get groups
No resources found
```

In KeyCloak, there exists a group named "house-admins" with one member, `larsks`. After I log into OpenShift with the corresponding credentials, we see on that OpenShift has created and populated the corresponding group:

```
$ k get groups
NAME           USERS
house-admins   larsks
```

On the KeyCloak side, I create a new group `house-metrics` and add `larsks` as a member. If I log out of OpenShift and log back in, we now see:

```
$ k get groups
NAME            USERS
house-admins    larsks
house-metrics   larsks
```
