### ISSUE TITLE
Creation of new Slack channel for alerts

### ISSUE THREAD

**Issue by computate** [OCP-on-NERC/operations#14]
Naved, could you please setup a new Slack channel for our alerts? It looks like I will need a webhook URL and the channel name. Here is the documentation for Slack Alerts and a sample config if it helps: 

https://prometheus.io/docs/alerting/latest/configuration/#slack_config

```yaml
global:
  slack_api_url: '<slack_webhook_url>'

route:
  receiver: 'slack-notifications'
  group_by: [alertname, datacenter, app]

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alerts'
    text: '[https://internal.myorg.net/wiki/alerts/{{](https://internal.myorg.net/wiki/alerts/%7B%7B) .GroupLabels.app }}/{{ .GroupLabels.alertname }}'
```
