### ISSUE TITLE
Load Kubeflow Pipelines in RHODS Pipelines 

### ISSUE THREAD

**Issue by Zongshun96** [OCP-on-NERC/operations#156]
# Description
It seems the Kubeflow Pipelines SDK cannot be used with RHODS Pipeline at the moment. The Kubeflow pipeline endpoint is not exposed.

Forwarding `ds-pipeline-pipelines-definition` service in my openshift project(ns) didn't solve the problem as my code (`kpf_tekton` with my `bearer token`, adapted from [here](https://github.com/rh-datascience-and-edge-practice/kubeflow-examples/blob/main/pipelines/1_test_connection.py)) complaining `certificate verify failed`. Also it is not safe to simply forward the service.

Trevor Royer commented the problem could be that "the container likely has a cert built into it that is self signed so your cert verification fails."

# Proposed Solution
Trevor suggested to add a route for the `oauth` port in the service, e.g., `oc create route reencrypt --service=dsp-def-service --port=oauth`. He mentioned "you can setup a route and the cluster will create a new cert that is already trusted for you."

<img width="1021" alt="Screen Shot 2023-06-30 at 5 31 58 PM" src="https://github.com/OCP-on-NERC/operations/assets/34226180/12e0306c-d4c3-4e32-beb7-724383db5390">

He also mentioned some workarounds. While I think we need a permenant fix to this problem, I am listing them here for record.
- "You can extract the cert from the container and add it to your trusted certs list on your machine"
- "`kpf_tekton` may provide an option to allow you to connect without authenticating the cert"

# Reproducibility
```
kfp_tekton~=1.5.0
https://github.com/adrien-legros/rhods-mnist/blob/main/docs/lab-instructions.md#add-a-pipeline-step
https://github.com/rh-datascience-and-edge-practice/kubeflow-examples/blob/main/pipelines/1_test_connection.py
```
Notes
- Please manually create the S3 bucket for your Pipeline Server. (Check `oc describe <pod>` and `AWS Cloudtrail`)
-  "The other gotcha that I have found is that in upstream you need to point kfp to `<route>/pipelines` and in dsp you will need to use just the route.  No `/pipelines`"
- "I think when you create a DSP instance it creates a pod called something like `data-science-pipelines-defenition` and the route for the API endpoint will be the one pointing towards that"
- "So basic rule of thumb is anything for connecting to the dsp server or compiling you want to use `kfp_tekton`.  Any normal pipeline defenition pieces use `kfp`."

**Comment by Zongshun96** [comment]
Now we need to figure out how to correctly configure the TLS params for the routes. 

Following tutorial (https://www.redhat.com/sysadmin/cert-manager-operator-openshift), we make sure that the cert-manager is running and I was able to create an `issuer` in my namespace.

Then we try to follow [this tutorial](https://github.com/cert-manager/openshift-routes#usage) to manually generate a certificate and add the secret to my route. There were two issues here. One I cannot create a certificate using the `ClusterIssuer` the certificate stays in `issuing` stage forever. Second, although I can create a certificate with the issuer in my namespace, after adding the TLS information to my route based on the secret generated by the certificate, I still saw the same `certificate verify failed`.

### Try to create `ClusterIssuer`
![Screen Shot 2023-07-13 at 4 14 13 PM](https://github.com/OCP-on-NERC/operations/assets/34226180/0e8c3414-0335-4d04-a71b-8fc1805b737f)
![Screen Shot 2023-07-13 at 4 14 20 PM](https://github.com/OCP-on-NERC/operations/assets/34226180/3e8b1b92-1db2-40b9-b8ba-9b4f26bf901e)


### Using `Issuer` in my namespace
![Screen Shot 2023-07-13 at 4 15 27 PM](https://github.com/OCP-on-NERC/operations/assets/34226180/914a3fc8-721b-4912-a182-a74af4d89e71)
![Screen Shot 2023-07-13 at 3 19 44 PM](https://github.com/OCP-on-NERC/operations/assets/34226180/a090e71f-de6e-47e5-826e-b52c69f0196d)
![Screen Shot 2023-07-13 at 3 22 22 PM](https://github.com/OCP-on-NERC/operations/assets/34226180/6788f7d8-b33d-4948-9ef0-3ca723e32bbd)
![Screen Shot 2023-07-13 at 3 23 04 PM](https://github.com/OCP-on-NERC/operations/assets/34226180/9eec6261-65b5-4ffc-8247-241c5a488a37)


# Next Attempt
Can we apply this [`cert-manager-openshift-routes`](https://github.com/cert-manager/openshift-routes#usage) in the test cluster and it should generate the certificate and populate my routes automatically.

**Comment by Zongshun96** [comment]
It turns out that without the [cert-manager-openshift-routes](https://github.com/cert-manager/openshift-routes#usage) we can still manualy setup certificate for routes and connect to KPF endpoint. While I think having this be automatically done in the test cluster would be nice, I have the steps to do so manually below.
Thank you for all the helps from Trevor and Dylan!

## Steps
1. Generate Certificate with `ClusterIssuer` (named `selfsigned` in NERC test cluster). It will create the corresponding secret in the same namespace/project.
![Screen Shot 2023-07-14 at 3 51 37 PM](https://github.com/OCP-on-NERC/operations/assets/34226180/60ea8ea8-b5eb-4fb2-9e0e-2e7712cb4a45)
![Screen Shot 2023-07-14 at 3 52 16 PM](https://github.com/OCP-on-NERC/operations/assets/34226180/df9e0f71-7121-4811-8452-b695a1ff4a01)

2. Copy & paste the cert and private key to your route. Configure your route with `spec.tls.termination: reencrypt`
![Screen Shot 2023-07-14 at 3 54 45 PM](https://github.com/OCP-on-NERC/operations/assets/34226180/6cb35eeb-3a09-420a-bedd-98926b86b3ed)

4. Add certificate to your kfp client in python (`kfp_tekton==1.5.0`).
```
client = kfp_tekton.TektonClient(
    host=kubeflow_endpoint,
    existing_token=bearer_token,
    ssl_ca_cert = '/home/ubuntu/Praxi-Pipeline/ca.crt'
)
```
5. Now, your kfp client should be able to connect to the kfp endpoint.
![Screen Shot 2023-07-14 at 4 10 25 PM](https://github.com/OCP-on-NERC/operations/assets/34226180/a6ce3ec4-afa8-429a-ad52-850ccce273df)
https://github.com/rh-datascience-and-edge-practice/kubeflow-examples/blob/main/pipelines/1_test_connection.py

**Comment by dystewart** [comment]
In the meantime we should document this as a solution. I also agree it would be nice to have an automated way of doing this. Nice work @Zongshun96!

**Comment by Zongshun96** [comment]
# Problem Description
I am facing a new error when deploying a kfp pipeline with intermediate data. The PVC is mounted to a volume but the container cannot mount that volume. 
It seems the cephfs/rbd Plugin pod is not working correctly(?). https://github.com/rook/rook/issues/4896#issuecomment-610186299


# Reproducibility 1
Deploying the pipeline below.
https://github.com/rh-datascience-and-edge-practice/kubeflow-examples/blob/0b3b0f837b1b7ea988e0c9242ca016dfec9f2bd6/pipelines/11_iris_training_pipeline.py

## Error Logs
<img width="1406" alt="Screen Shot 2023-07-19 at 12 47 26 AM" src="https://github.com/OCP-on-NERC/operations/assets/34226180/284f4e36-9d37-42ac-b08d-93c0ee4d3f4e">
<img width="1774" alt="Screen Shot 2023-07-19 at 12 47 04 AM" src="https://github.com/OCP-on-NERC/operations/assets/34226180/efc2bf27-ea8b-43c4-bef3-d81daf48e6dd">

# Reproducibility 2
Deploying a single container pod with a PVC also shows the same error.

interm-pvc.yaml
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: interm-pvc
  namespace: praxi 
  # labels:
  #   app: snapshot
spec:
  storageClassName: ocs-external-storagecluster-ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

```

fake-deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapshot-fake-deployment
  namespace: praxi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snapshot
  template:
    metadata:
      labels:
        app: snapshot
    spec:
      containers:
        - name: snapshot-fake
          image: busybox:latest
          imagePullPolicy: "IfNotPresent"
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          volumeMounts:
            - mountPath: /fake-snapshot
              name: snapshot-vol1
      volumes:
        - name: snapshot-vol1
          persistentVolumeClaim:
            claimName: interm-pvc
```

## Error Logs
<img width="1312" alt="Screen Shot 2023-07-19 at 1 00 40 AM" src="https://github.com/OCP-on-NERC/operations/assets/34226180/070195dd-95ee-4dcf-91c2-b8b55ffae1de">
<img width="1505" alt="Screen Shot 2023-07-19 at 1 02 50 AM" src="https://github.com/OCP-on-NERC/operations/assets/34226180/08e2e880-3130-4179-b8d4-c8cfda91e18a">
