### ISSUE TITLE
Debugging external-apps-ingress-controller in Prod cluster

### ISSUE THREAD

**Issue by dystewart** [OCP-on-NERC/operations#29]
I've done some looking around and I'm seeing what may be a typo in the ingressController yaml file on this [line](https://github.com/OCP-on-NERC/nerc-ocp-config/blob/9634fb802ded8f3e51d853711bae33ca2c526d7a/cluster-scope/overlays/nerc-ocp-prod/ingresscontrollers/external-apps-ingress-controller.yaml#L7)

I'm assuming it's meant to be:
```
spec:
  domain: apps.openshift.nerc.mghpcc.org
```
As opposed to:
```
spec:
  domain: apps.shift.nerc.mghpcc.org
```

This may not be the only thing that needs changing seeing as there is also something going on with the node scheduling as seen in the conditions [here](https://console-openshift-console.apps.nerc-ocp-prod.rc.fas.harvard.edu/k8s/ns/openshift-ingress-operator/operator.openshift.io~v1~IngressController/external-apps-ingress-controller), but it's a start.

**Comment by larsks** [comment]
See my comment on the PR: the original value was correct (and you can verify that with a simple DNS query; compare the result of looking up `foo.apps.shift.nerc.mghpcc.org` with `foo.apps.openshift.mghpcc.org`).

**Comment by larsks** [comment]
And to avoid some additional confusion: there is some overlap between this issue and with https://github.com/OCP-on-NERC/operations/issues/16. This issue is supposed to be "Why isn't the external ingress controller running?"

**Comment by dystewart** [comment]
It looks like the reason the external ingressController is not creating is because the pods are not schedule-able (See the PodsScheduled status at: [here](https://console-openshift-console.apps.nerc-ocp-prod.rc.fas.harvard.edu/k8s/ns/openshift-ingress-operator/operator.openshift.io~v1~IngressController/external-apps-ingress-controller) 

I quickly looked through the nodes available to the prod cluster and I don't see any labels (zone: external) which as you can see in the ingressController yaml, it's looking for
```
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: external-apps-ingress-controller
  namespace: openshift-ingress-operator
spec:
  domain: apps.shift.nerc.mghpcc.org
  defaultCertificate:
    name: external-apps-ingress-certificate
  endpointPublishingStrategy:
    type: LoadBalancerService
    loadBalancer:
      scope: External
  nodePlacement:
    nodeSelector:
      matchLabels:
        zone: external
  namespaceSelector:
    matchLabels:
      type: external
```

On several of the prod cluster's worker nodes there is however a label (nerc.mghpcc.org/external-ingress: 'true') which appears to be the label we are actually looking for. I think the namespace label may become an issue as well but the main error is related to the nodeselector so I'm going to open a PR to see about making this change and will link it below.
